=== lefebvreariane/m2-2012-projet/src/scenes/scene.dtd
<!ELEMENT scene (units, matrix,punch,sheet)>

<!ELEMENT units (time, distance)>
<!ELEMENT time EMPTY>
<!ATTLIST time
    timeUnit (ms|s) "s"
    duration CDATA #REQUIRED
>
<!ELEMENT distance EMPTY>
<!ATTLIST distance
    distanceUnit (um|mm|cm) "mm"
    xAxis CDATA #REQUIRED
    yAxis CDATA #REQUIRED
>

<!ELEMENT matrix (point+)>
<!ATTLIST matrix closedMatrix (True|False) #IMPLIED>

<!ELEMENT punch (point+, transformation)>
<!ATTLIST punch closedPunch (True|False) #IMPLIED>
<!ELEMENT transformation (translation|rotation)>
<!ELEMENT translation EMPTY>
<!ATTLIST translation
    xTranslation CDATA #REQUIRED
    yTranslation CDATA #REQUIRED
>

<!ELEMENT sheet (line|curve)+>
<!ATTLIST sheet thickness CDATA "2">
<!ELEMENT line (point, point)>
<!ELEMENT curve (point+, node+, degree)>
<!ELEMENT node EMPTY>
<!ATTLIST node n CDATA #REQUIRED>
<!ELEMENT degree EMPTY>
<!ATTLIST degree d CDATA #REQUIRED>

<!ELEMENT point EMPTY>
<!ATTLIST point
    fixed (True|False) #IMPLIED
    x CDATA #REQUIRED
    y CDATA #REQUIRED
>

=== lefebvreariane/m2-2012-projet/src/scenes/sceneTest1.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE scene SYSTEM "scene.dtd">
<scene>
    <units>
        <time timeUnit="s" duration="40"/>
        <distance distanceUnit="mm" xAxis="20" yAxis="20"/>
    </units>
    <matrix closedMatrix="True">
        <point x="0" y="0"/>
        <point x="0" y="10"/>
        <point x="10" y="10"/>
        <point x="10" y="0"/>
        <point x="0" y="0"/>
    </matrix>
    <punch closedPunch="True">
        <point x="11" y="20"/>
        <point x="20" y="20"/>
        <point x="20" y="15"/>
        <point x="11" y="15"/>
        <point x="11" y="20"/>
        <transformation>
            <translation xTranslation="0" yTranslation="-10"/>
        </transformation>
    </punch>
    <sheet thickness="2">
        <line>
            <point x="0" y="0"/>
            <point x="20" y="0"/>
        </line>
    </sheet>
</scene>
